export const fontes = [
	{ value: 'Arial', name: 'Arial' },
	{ value: 'Helvetica', name: 'Helvetica' },
	{ value: 'Verdana', name: 'Verdana' },
	{ value: 'Tahoma', name: 'Tahoma' },
	{ value: 'Calibri', name: 'Calibri' },
	{ value: 'Geneva', name: 'Geneva' },
	{ value: 'Trebuchet MS', name: 'Trebuchet MS' },
	{ value: 'Times New Roman', name: 'Times New Roman' },
	{ value: 'Georgia', name: 'Georgia' },
	{ value: 'Garamond', name: 'Garamond' },
	{ value: 'Palatino', name: 'Palatino' },
	{ value: 'Book Antiqua', name: 'Book Antiqua' },
	{ value: 'Serifa', name: 'Serifa' },
	{ value: 'Cambria', name: 'Cambria' },
	{ value: 'Courier New', name: 'Courier New' },
	{ value: 'Consolas', name: 'Consolas' },
	{ value: 'Monaco', name: 'Monaco' },
	{ value: 'Andale Mono', name: 'Andale Mono' },
	{ value: 'Liberation Mono', name: 'Liberation Mono' },
	{ value: 'Comic Sans MS', name: 'Comic Sans MS' },
	{ value: 'Impact', name: 'Impact' },
	{ value: 'Lucida Sans Unicode', name: 'Lucida Sans Unicode' },
	{ value: 'Arial Black', name: 'Arial Black' },
	{ value: 'Courier', name: 'Courier' },
	{ value: 'Fantasy', name: 'Fantasy' },
	{ value: 'Nunito Sans', name: 'Nunito Sans' },
	{ value: 'Cursive', name: 'Cursive' },
	{ value: 'Monospace', name: 'Monospace' },
	{ value: 'System', name: 'System' },
	{ value: 'UI', name: 'UI' }
]
